version: '3'

services:

  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: whatever
      MYSQL_DATABASE: bucketlist
      MYSQL_USER: flask_app
      MYSQL_PASSWORD: whatever
    volumes:
    - my_own_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"  

  flask:
    build: .
    depends_on:
      - mysql_db
    ports:
      - 5002:5002
    environment:
      - DB_HOST=mysql_db  
volumes:
 my_own_data:     