version: '3'

services:

  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: whatever
      MYSQL_DATABASE: BucketList
      MYSQL_USER: flask_app
      MYSQL_PASSWORD: whatever
    volumes:
    - my_own_data:/var/lib/mysql
    ports:
      - "3306:3306"  

  flask:
    build: .
    depends_on:
      - mysql_db
    ports:
      - 5000:5000
    environment:
      - DB_HOST = mysql_db
      - DB_PORT = 3306
      - DB_USER = flask_app
      - DB_PASSWORD = whatever
      - DB_NAME = BucketList 
volumes:
 my_own_data:     